---
title: "SoCal Data Science Bootcamp"
subtitle: "Summer 2022 Schedule"
output: 
  html_document:
    css: "style.css"
    toc: true
    toc_depth: 2
    toc_float: true
---


## Before the Bootcamp

- **Sign up for GitHub** [`r fontawesome::fa(name = "link")`](https://github.com) Sign up for a free GitHub account if you don't already have one. Make sure to pick a username that you feel comfortable sharing on your CV. You will most likely use your GitHub username for many years in your data science career. Fill out [this survey](https://forms.gle/SnXs9u6coACkdDGEA) to let us know what your username is. 

- **Install R** [`r fontawesome::fa(name = "link")`](https://mirror.las.iastate.edu/CRAN/) Yes, you do need to download and install R even if you have downloaded before. There is a newer version.

- **Install RStudio** [`r fontawesome::fa(name = "link")`](https://www.rstudio.com/products/rstudio/download/) Yes, you do need to download and install RStudio even if you have downloaded before. There is a newer version. Download the free Desktop version.


- **Install and setup git** [`r fontawesome::fa(name = "video")`](https://uci.yuja.com/V/Video?v=3637094&node=12339053&a=1176648183&autoplay=1) [`r fontawesome::fa(name = "chalkboard-teacher")`](https://www.introdata.science/slides/week00/00a-git-github-install.html#1)

- **Test your installations**  [`r fontawesome::fa(name = "video")`](https://uci.yuja.com/V/Video?v=4810457&node=15922642&a=1712193560&autoplay=1)


## Day 1

| Topic                         | Materials |
|-------------------------------|-----------|
| Introduction to Toolkit       |[`r fontawesome::fa(name = "desktop")`](slides/day01-intro-toolkit/01a-intro-toolkit.html)           |
| Summarizing Data with Numbers |[`r fontawesome::fa(name = "desktop")`](slides/day01-intro-toolkit/01b-summarizing-data.html)                    |
| Visualizing Data              |[`r fontawesome::fa(name = "desktop")`](slides/day01-intro-toolkit/01c-visualizing-data.html)           |

## Day 2

| Topic                         | Materials |
|-------------------------------|-----------|
| Changing Variables       |[`r fontawesome::fa(name = "desktop")`](slides/day02-wrangle-data/02a-changing-variables.html)           |
| Subsetting Data |[`r fontawesome::fa(name = "desktop")`](slides/day02-wrangle-data/02b-subsetting-data.html)                    |
| Joining Data              |[`r fontawesome::fa(name = "desktop")`](slides/day02-wrangle-data/02c-joining-data.html)           |

## Day 3

| Topic                         | Material |
|-------------------------------|-----------|
| Simple Linear Regression       |[`r fontawesome::fa(name = "desktop")`](slides/day03-regression/03a-simple-linreg.html)           |
| Multiple Linear Regression |[`r fontawesome::fa(name = "desktop")`](slides/day03-regression/03b-multiple-linreg.html)                   |




## Day 4

| Topic                         | Material |
|-------------------------------|-----------|
| Reproducible Workflow       |[`r fontawesome::fa(name = "desktop")`](slides/day04-work04a-reproducible-workflow.html)           |